# Generated by Django 4.1.3 on 2023-03-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_on_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='expected_loan_interest_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='loan_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='loan_grade',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='loan_intent',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='profile',
            name='person_age',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='person_emp_length',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='person_home_ownership',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='person_income',
            field=models.FloatField(default=0),
        ),
    ]
