# Generated by Django 4.1.3 on 2023-03-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_default_on_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='default_on_file',
            new_name='cb_person_default_on_file',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='loan_amount',
            new_name='loan_amnt',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='expected_loan_interest_rate',
            new_name='loan_int_rate',
        ),
        migrations.AddField(
            model_name='profile',
            name='cb_person_cred_hist_length',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='loan_percent_income',
            field=models.FloatField(default=0),
        ),
    ]
