# Generated by Django 4.1.3 on 2023-04-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_liquid_funds'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_borrower',
            field=models.BooleanField(default=False),
        ),
    ]
